### ISSUE TITLE
A woman getting murdered as a project image?

### ISSUE THREAD

**Issue by selfawaresoup** [necolt/Swifton#3]
Would you reconsider using [this photo](https://camo.githubusercontent.com/13630d58359ab0039ff2fa5df9675cc0828c4304/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4273704d396e43436341414b63696a2e6a7067) to represent this project? Is this the message you want to send to someone who sees this project page for the first time?

EDIT: Not to mention that it's probably a copyright infringement.

**Comment by hagenburger** [comment]
:+1:

**Comment by ojss** [comment]
it really is quite funny...
on serious note, agreed.

**Comment by sauliusgrigaitis** [comment]
Thanks. I linked picture of Swift Taylor with Youtube video so everyone can see that this was performance and she is alive and well.

**Comment by rentalcustard** [comment]
It's not clear until you hover over the video that it's now a link.

The question is not "is this an depiction of a woman being killed in reality, or a performance thereof", but "is it a good idea to have a depiction of a woman being killed on this project page?" Linking to a Taylor Swift video will allow people (if they stay on the page long enough to notice the link) to understand the connection and the visual pun. However, I remain unconvinced that this visual pun is funny/clever enough to justify the risk of people not understanding it and feeling uncomfortable, or even understanding it and _continuing_ to feel uncomfortable, because the image does depict a violent act.

**Comment by ojss** [comment]
really now? There is a huge text in bold that says "Swift on Rails" right underneath the image. Common let there be some humor :smile:

**Comment by rentalcustard** [comment]
@ojss that huge text works to explain the visual pun if you recognize the person in the image as Taylor Swift, or if you click the image to find out who it is.

Even if you make the connection, as I argued above, you might well still feel uncomfortable - rather than amused - with the use of the image, and draw adverse conclusions about this project.

**Comment by MySidesTheyAreGone** [comment]
Subscribed. Please keep discussing this issue.

**Comment by sauliusgrigaitis** [comment]
So something like "Taylor Swift sitting on the rails during performance" written under the picture should solve the problem completely? Even more, visitor can watch video and find out that she is alive and well.

**Comment by MySidesTheyAreGone** [comment]
I don't know man, that image is pretty realistic. Lots of victims watch straight into the camera and make a pretty O with their mouths while being murdered. I think this issue needs more discussion.

**Comment by selfawaresoup** [comment]
Please ask yourself, if a quick laugh about a Taylor Swift reference is worth alienating users and potential contributors from your project. Of course, you're free to keep the image but be aware that it will drive people away.

@sauliusgrigaitis It is not about the well-being of the actual person depicted. We all know that Taylor Swift is most likely alive and well. It's about the message you are sending with it. It says "In this project we make casual jokes about violence against women.", especially since it's literally the first thing on the page, before any actual information about the project. Personally, when I see this I ask myself: "Do I want to work with this project, given this information?" and the answer is "No".

**Comment by sauliusgrigaitis** [comment]
Thanks. What about some other picture from the clip? Something like https://www.youtube.com/watch?v=jYa1eI1hpDE&feature=youtu.be&t=224 ?

**Comment by selfawaresoup** [comment]
@sauliusgrigaitis if you _really_ insist on that reference, yes, that scene is better. And I'm still not sure about the legal side of using it here (copyright) but I don't really care about that, honestly.

**Comment by heygambo** [comment]
Haha I love that picture. I just didn't know that this is Taylor Swift.

**Comment by x1024** [comment]
I found a link to this thread and it brought the project to my attention.

I like people with a sense of humor and I'd love to help contribute in some way, @sauliusgrigaitis do you have a list of outstanding issues?

**Comment by habibalamin** [comment]
Why do you rail so hard (hehe) against depictions of “violence against women”, yet we don't hear a peep from people like you (vague, I know, but I think we all know who we're talking about) when it comes to, for example, action movies, where men are killed by the thousands? This is why people don't take people like you seriously, and if you weren't so hell-bent on trying to go after people's employers, there'd be a lot more blowback against this sort of trojan horse in the community.

Just so we're clear what we're even arguing about, the joke isn't even predicated on the subject being a woman, it's a wordplay on the singer's name and her being on the rails. The character happened to be a woman, but it's in no way a requirement. Not that that matters, IMHO, but we should be clear about what we're arguing about.

Even if they don't get the pun, I doubt the vast majority of people will look at that image and assume that people are laughing at the depiction of violence against women. I would bet most people would just think, “I don't get it” and move on.

> However, I remain unconvinced that this visual pun is funny/clever enough to justify the risk of people not understanding it and feeling uncomfortable, or even understanding it and continuing to feel uncomfortable, because the image does depict a violent act.

Have you sworn off Tom & Jerry and The Roadrunner, too? How about action movies or adventure games or any kind of literature with violence?

> Please ask yourself, if a quick laugh about a Taylor Swift reference is worth alienating users and potential contributors from your project. Of course, you're free to keep the image but be aware that it will drive people away.

I think it's worth mentioning that there will be far more people that see the image and draw positive conclusions about the project. I know I did. I smiled at the wordplay and made a mental note to myself to hurry up with learning Swift. If we're strictly talking about what kind of impression the project maintainer is making on other people and whether this will drive people away or drive people to contribute, I would say the latter is far more likely.

@sauliusgrigaitis I doubt there's any good faith here. I think the request is absurd, and there's no reason for you to entertain it before we've even had the conversation (and there's no obligation on you to have it). There's been a trend recently of these people pestering open-source projects to adopt their stance until the maintainer just gives up, often with additional pressure from tons of brand new accounts or accounts with zero (or very little) contributions to any repo that isn't just more of the same pestering (if you can call that a contribution). Some might even call it harassment.

**Comment by sauliusgrigaitis** [comment]
Thanks a lot everyone for feedback. Let's discuss.

**Comment by sauliusgrigaitis** [comment]
@x1024 thanks, I opened few issues.

**Comment by N0rav0** [comment]
I really wouldn't worry what some Eurotrash beta males have to say. For people who contribute so little it's a wonder they're even allowed on the American internet.

**Comment by lepasserby** [comment]
Dear @sauliusgrigaitis please check out this fine essay by Meredith Patterson to learn what exactly you are dealing with here.
http://status451.com/2015/12/21/totalizing-politics-and-insurance-rackets/

**Comment by habibalamin** [comment]
@N0rav0 let's please not clog up the issue, it just creates a massive wall that won't allow either side's message to get across.

If you firmly believe that in an environment conducive to actually discussing the issues like the intelligent adults we are, your side will completely demolish the other sides' grade school arguments, then it's in your best interests to let it happen. If you don't, then maybe the other side has something useful to say, even if they're wrong in their conclusion.

Let's please not turn this into Opalgate.

**Comment by Maelses** [comment]
Do you really want anyone who doesn't get the pun to contribute anyway? Or anyone that's genuinely offended?

**Comment by LegoStormtroopr** [comment]
Chiming in to say that image is pretty funny. It's literally Swift... on rails.

If we are talking about first impressions, the image to me says:

> This team is clever, understands visual puns, doesn't take it self to seriously and likes Taylor Swift.

I like all these things, so I would want to join this team. That's the trouble with communication, you can't control how people interpret your message. That's entirely on them.

**Comment by Sword-play** [comment]
Why are we pretending that women are people?

**Comment by KBryan** [comment]
This is a cool project, to be taken seriously a proper logo. Should be constructed. Willing to put one together.

**Comment by MrMagoffin** [comment]
Popping in to say that this is some neat work you're doing, and the image you're using is fantastic. Certainly caught my attention.

**Comment by digiwombat** [comment]
I like TayTay and her sexy legs so I vote you keep it.

The picture you use is a non-issue. This is another attempt to drum it up and get a bunch of people who've never committed to the project to come in and have an opinion about how it's stopping them from enjoying open source. Well, I'll be one of the never-committed-to-the-project people on the other side.

It's all fine. Ignore non-issue, pop-culture trolls and they will go away. They want soft targets.

Also, @lnwdr, if you're so concerned, why not just fork it and change the logo and call it SafeSwiftOnRails or something? Why not have an alternative version for people of your particular sensibility/point-of-view that just pulls changes downstream but keeps the logo free of pop-culture references so ubiquitous that they date back to the late 1800s?

**Comment by califrench** [comment]
I like the pic! I thought it was funny and Taylor Swift is quite nice looking.

**Comment by xnth97** [comment]
Just relax and keep that pic. I love that image as a TS fan and I admire the humor, making me even more willing to contribute if I could.

**Comment by habibalamin** [comment]
Too late, it's gonna be a crash landing… brace yourselves, people.

**Comment by opyh** [comment]
Even if it is 'just a pun', the problem is that even the things that are just a little alienating add up. To me this looks like one of the typical artifacts that make IT scene look like some men's club. I'm sure we can find a better pun that's a bit more inclusive :)

**Comment by selfawaresoup** [comment]
@opyh: Thanks. Exactly.

@digiwombat: If you actually would have read my comments carefully, you'd know that I haven't asked to remove the picture. I only pointed out that it might be alienating to some people. It's in the project maintainer's hands to decide. So, please keep your personal attacks to yourself. You are not helping anyone.

**Comment by Maelses** [comment]
Nobody cares about your non-issue. This is being kept open because it's generating exposure for the project, not because anyone actually cares (including yourselves). Nobody buys that you are piping up for any reason other than to create controversy where there is none. No one buys it.

If you are alienated by the project image, seek medical help immediately. If you came to defend people feeling alienated, seek medical help immediately. You are just as sick.

**Comment by LegoStormtroopr** [comment]
> To me this looks like one of the typical artifacts that make IT scene look like some men's club.

Yes to you it looks like that. I won't deny you that. To me, and probably to many others, it's a clever visual pun.

Furthermore, its an image from a video clip made by one of the 21st centurys biggest feminist icons that lambasts early cinema tropes.

Wouldn't that be _attractive_ to likeminded people knowing that the maintainers of this project know and enjoy the work of a prominent feminist?

**Comment by skade** [comment]
@sauliusgrigaitis I recommend turning this issue into "for contributors only" for a while.

@Maelses I'm not the keeper of the house here, but please refrain from insults and speculation about others people mental health.

In general: I find the picture unnecessary. It's a weird distraction to many. Every side of the debate will claim that they are the "many". It's a shale pun on the programming language name that has been done a hundred times.

FWIW: I'm on "why that picture?" side.

Also, note that there are several additional problems with this:

a) the picture is copyrighted
b) the name Rails is trademarked and should only be used when pointing to "Ruby on Rails". This is exercised and lead to the renaming of "Groovy on Grails".

http://rubyonrails.org/trademarks/
http://grails.1312388.n4.nabble.com/Groovy-on-Rails-is-no-more-kind-of-td1313422.html

Get a clever name that doesn't rely on another project, just for the sake of a pun.

Swifton is a great name. It's far better then a long name playing on something else. Drop the pun, use the short name, get recognizable on your own.

**Comment by LegoStormtroopr** [comment]
@skade

Also, note that there are several problems with this:

a) the picture is clearly fair use
b) the name Rails is trademarked and should only be used when pointing to "Ruby on Rails" _for Ruby projects only_

I can make a "c on rails" or "go on rails" or "brainfuck on rails" and they are all valid projects that RoR has any authority over.

**Comment by skade** [comment]
> I can make a "c on rails" or "go on rails" or "brainfuck on rails" and they are all valid projects that RoR has any authority over.

Talk to your trademark lawyer about that. Also, see my edit that there are prior cases (although they did that as a courtesy).

Also, I'm not interested in discussing that point further. Thanks in advance for honoring that.

**Comment by LegoStormtroopr** [comment]
I honor nothing.

The thing about trademarks is they have to be defended. If Ruby on Rails want to go around suing every project that uses the word rails then thats fine, but the onus is on them and no one else.

Until Ruby on Rails makes a claim then "Swift on Rails" is a valid project name.

Now excuse me I'm going to Xerox my Photoshop of this picture I Googled of someone Hoovering up a Kleenex before I host it on my Rails blog.

Edit: I forgot Spam.

**Comment by LegoStormtroopr** [comment]
I've got a really boring projecr going on and am begging for contributors. If I post a picture of Taylor Swift in the README will I get contributors then?

**Comment by heygambo** [comment]
Taylor Swift on Rails. Man close the issue. It's perfect.

**Comment by kstarikov** [comment]
Nice thread. Definitely attracted my attention to this promising project.

**Comment by abbasfaisal** [comment]
That picture, probably the reason I am here navigating the issues to see if I can contribute. Though I didn't notice it had a link until read here.

**Comment by reesemclean** [comment]
Thank you everyone for your responses. It is clear that this project does not listen to to constructive feedback when it comes to issues around being inclusive.

There are plenty of Swift web frameworks popping up; what will decide on which ones take off is really dependent on who can build the best community. So far by insisting on keeping an image as your logo - a copyrighted one that you have no right to use anyway - that some people have told you makes them hesitant to want to contribute, shows you don't have what it takes to foster an inclusive project.

**Comment by sauliusgrigaitis** [comment]
I'm closing this issue until someone can come with great logo to replace this picture. Naturally some people like current picture and some people doesn't like, it's free world. If anyone has art skills and would love to contribute great logo - please ping me!
